defaults: &defaults
  macos:
    xcode: "10.0.0"
  environment:
    ARTIFACTS: /artifacts
  working_directory: ~/ddev-ui

version: 2.0
jobs:
  build:
    <<: *defaults
    steps:
      # Checkout the codebase
      - restore_cache:
          keys:
            - v2-source-{{ .Branch }}-{{ .Revision }}
            - v2-source-{{ .Branch }}-
      - checkout
      - save_cache:
          key: v2-source-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
            - ~/ddev-ui

      # Homebrew Setup
      - restore_cache:
          keys:
            - v2-homebrew-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - v2-homebrew-{{ .Branch }}-
      ## xquartz setup
      - run:
          name: xquartz setup
          command: brew cask install xquartz || true
      ## wine setup
      - run:
          name: Homebrew install of wine
          command: brew install wine || true
      ## save cache
      - save_cache:
          key: v2-homebrew-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /usr/local/Caskroom/xquartz
            - /usr/local/Cellar/wine

      # build app dependancies
      ## yarn install
      - restore_cache:
          keys:
            - v2-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v2-yarn-packages-{{ .Branch }}-
      - run:
          name: Yarn Install
          command: yarn install
      ## yarn cache
      - save_cache:
          key: v2-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/ddev-ui/node_modules

      ## echo installed tools
      - run:
          name: Installed tool versions
          command: >-
            echo "git commit=$(make version) node version=$(node --version) npm
            version=$(npm --version) wine version=$(wine --version) HOME=$HOME
            USER=$(whoami) PWD=$PWD"

      # build apps
      # - run: make all
      - run: make

  test:
    <<: *defaults
    steps:
      # Checkout the codebase
      - restore_cache:
          keys:
            - v2-source-{{ .Branch }}-{{ .Revision }}
            - v2-source-{{ .Branch }}-
      - checkout
      # Homebrew Setup
      - restore_cache:
          keys:
            - v2-homebrew-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - v2-homebrew-{{ .Branch }}-
      - run: brew update || brew update || true
      # Yarn setup
      - restore_cache:
          keys:
            - v2-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v2-yarn-packages-{{ .Branch }}-
      - run:
          name: Yarn Install
          command: yarn install

      # run tests
      - run: make test

  artifacts:
    <<: *defaults
    steps:
      # Checkout the codebase
      - restore_cache:
          keys:
            - v2-source-{{ .Branch }}-{{ .Revision }}
            - v2-source-{{ .Branch }}-
      - checkout
      # Homebrew Setup
      - restore_cache:
          keys:
            - v2-homebrew-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - v2-homebrew-{{ .Branch }}-
      - run: brew update
      # Yarn setup
      - restore_cache:
          keys:
            - v2-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v2-yarn-packages-{{ .Branch }}-
      - run:
          name: Yarn Install
          command: yarn install

      - run:
          command: ./.circleci/generate_artifacts.sh $ARTIFACTS
          name: tar/zip up artifacts and make hashes

      - store_artifacts:
          path: /artifacts

  deploy:
    <<: *defaults
    steps:
      # Checkout the codebase
      - restore_cache:
          keys:
            - v2-source-{{ .Branch }}-{{ .Revision }}
            - v2-source-{{ .Branch }}-
      - checkout
      # Homebrew Setup
      - restore_cache:
          keys:
            - v2-homebrew-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - v2-homebrew-{{ .Branch }}-
      - run: brew update
      # Yarn setup
      - restore_cache:
          keys:
            - v2-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v2-yarn-packages-{{ .Branch }}-
      - run:
          name: Yarn Install
          command: yarn install

      # only release Darwin for now
      - run: make release-darwin
      # - run: make release

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - artifacts:
          requires:
            - build
            - test
          filters:
            branches:
              ignore:
                - master
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - master
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
