defaults: &defaults
  macos:
    xcode: "9.4.1"
  environment:
    ARTIFACTS: /artifacts
  working_directory: ~/ddev-ui

version: 2.0
jobs:
  build:
    <<: *defaults
    steps:
      # Checkout the codebase
      - restore_cache:
          keys:
            - v2-source-{{ .Branch }}-{{ .Revision }}
            - v2-source-{{ .Branch }}-
      - checkout
      - save_cache:
          key: v2-source-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
            - ~/ddev-ui

      # Homebrew Setup
      - restore_cache:
          keys:
            - v2-homebrew-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - v2-homebrew-{{ .Branch }}-
      ## Homebrew update
      - run:
          name: Homebrew setup
          command: brew update

      ## xquartz setup
      - run:
          name: xquartz setup
          command: brew cask install xquartz
      ## wine setup
      - run:
          name: Homebrew install of wine
          command: |
            brew install wine || true
            brew unlink wine && brew link --overwrite wine
      ## save cache
      - save_cache:
          key: v2-homebrew-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /usr/local/Homebrew
            - /usr/local/Caskroom/xquartz
            - /usr/local/Cellar/wine

      # build app dependancies
      ## yarn install
      - restore_cache:
          keys:
            - v2-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v2-yarn-packages-{{ .Branch }}-
      - run:
          name: Yarn Install
          command: yarn install
      ## yarn cache
      - save_cache:
          key: v2-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/ddev-ui/node_modules

      ## echo installed tools
      - run:
          name: Installed tool versions
          command: >-
            echo "git commit=$(make version) node version=$(node --version) npm
            version=$(npm --version) wine version=$(wine --version) HOME=$HOME
            USER=$(whoami) PWD=$PWD"

      # build apps
      # - run: make all
      - run: make

      # all other test jobs will run AFTER this build job finishes
      # to avoid reinstalling dependencies, we persist the source folder "app"
      # and the Cypress binary to workspace, which is the fastest way
      # for Circle jobs to pass files
      - persist_to_workspace:
          root: ~/
          paths:
            - ddev-ui
            - .cache

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/

      # Homebrew Setup
      - restore_cache:
          keys:
            - v2-homebrew-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - v2-homebrew-{{ .Branch }}-

      ## echo installed tools
      - run:
          name: Installed tool versions
          command: >-
            echo "git commit=$(make version) node version=$(node --version) npm
            version=$(npm --version) wine version=$(wine --version) HOME=$HOME
            USER=$(whoami) PWD=$PWD"

      - run: make test

  artifacts:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/

      # Homebrew Setup
      - restore_cache:
          keys:
            - v2-homebrew-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - v2-homebrew-{{ .Branch }}-

      ## echo installed tools
      - run:
          name: Installed tool versions
          command: >-
            echo "git commit=$(make version) node version=$(node --version) npm
            version=$(npm --version) wine version=$(wine --version) HOME=$HOME
            USER=$(whoami) PWD=$PWD"

      - run:
          command: ./.circleci/generate_artifacts.sh $ARTIFACTS
          name: tar/zip up artifacts and make hashes

      - store_artifacts:
          path: /artifacts

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/

      # Homebrew Setup
      - restore_cache:
          keys:
            - v2-homebrew-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - v2-homebrew-{{ .Branch }}-

      ## echo installed tools
      - run:
          name: Installed tool versions
          command: >-
            echo "git commit=$(make version) node version=$(node --version) npm
            version=$(npm --version) wine version=$(wine --version) HOME=$HOME
            USER=$(whoami) PWD=$PWD"

      # only release Darwin for now
      - run: make release-darwin
      # - run: make release

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - artifacts:
          requires:
            - build
            - test
      - deploy:
          requires:
            - build
            - test
