defaults: &defaults
  macos:
    xcode: "9.4.1"
  environment:
    ARTIFACTS: /artifacts
  working_directory: ~/ddev-ui

version: 2.1
jobs:
  build:
    <<: *defaults
    steps:
      # Checkout the codebase
      - restore_cache:
          keys:
            - v1-source-{{ .Branch }}-{{ .Revision }}
            - v1-source-{{ .Branch }}-
      - checkout
      - save_cache:
          key: v1-source-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
            - ~/ddev-ui

      # Homebrew Setup
      - restore_cache:
          keys:
            - v1-homebrew-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - v1-homebrew-{{ .Branch }}-
      ## homebrew update
      - run:
          name: homebrew setup
          command: brew update

      ## xquartz setup
      - run:
          name: xquartz setup
          command: brew cask install xquartz
      ## wine setup
      - run:
          name: Homebrew install of wine
          command: |
            brew install wine || true
            brew unlink wine && brew link --overwrite wine
      ## save cache
      - save_cache:
          key: v1-homebrew-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /usr/local/Homebrew
            - /usr/local/Caskroom/xquartz
            - /usr/local/Cellar/wine

      # build app dependancies
      ## yarn install
      - restore_cache:
          keys:
            - v1-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-yarn-packages-{{ .Branch }}-
      - run:
          name: Yarn Install
          command: yarn install
      ## yarn cache
      - save_cache:
          key: v1-yarn-packages{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      ## echo installed tools
      - run:
          name: Installed tool versions
          command: >-
            echo "git commit=$(make version) node version=$(node --version) npm
            version=$(npm --version) wine version=$(wine --version) HOME=$HOME
            USER=$(whoami) PWD=$PWD"

      # build apps
      - run: make all

      - run:
          command: ./.circleci/generate_artifacts.sh $ARTIFACTS
          name: tar/zip up artifacts and make hashes

      - store_artifacts:
          path: /artifacts

      - run: make test

      # only release Darwin for now
      - run: make release-darwin
      # - run: make release

      # all other test jobs will run AFTER this build job finishes
      # to avoid reinstalling dependencies, we persist the source folder "app"
      # and the Cypress binary to workspace, which is the fastest way
      # for Circle jobs to pass files
      # - persist_to_workspace:
      #     root: ~/
      #     paths:
      #       - ddev-ui
      #       - dist
      #       - .npm
      #       - .cache
      #       - /usr/local/Homebrew
      #       - /usr/local/Caskroom/xquartz
      #       - /usr/local/Cellar/wine
