version: 2.1

executors:
  mac-executor:
    macos:
      xcode: "9.0"
    environment:
      ARTIFACTS: /artifacts
    working_directory: ~/ddev-ui

jobs:
  # checkout code base
  checkout_code:
    executor: mac-executor
    steps:
      # checkout
      - checkout
      # cache codebase
      - save_cache:
          key: repo-v1-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/ddev-ui

  # build env dependancies
  build_env_dependencies:
    executor: mac-executor
    steps:
      # restore codebase
      - restore_cache:
          keys:
            - repo-v1-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - repo-v1-

      # restore brew cache
      - restore_cache:
          keys:
            - homebrew-v1-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - homebrew-v1-{{ .Branch }}-
            - homebrew-v1-

      # homebrew update
      - run:
          name: homebrew setup
          command: brew update

      # xquartz setup
      - run:
          name: xquartz setup
          command: brew cask install xquartz
      - run:
          name: Homebrew install of node --lts
          command: |
            brew unlink node || true
            brew install node@8 || true
            brew link --overwrite --force node@8
      - run:
          name: Homebrew install of wine
          command: |
            brew install wine || true
            brew unlink wine && brew link --overwrite wine
      - run:
          name: Installed tool versions
          command: >-
            echo "git commit=$(make version) node version=$(node --version) npm
            version=$(npm --version) wine version=$(wine --version) HOME=$HOME
            USER=$(whoami) PWD=$PWD"
      - save_cache:
          key: homebrew-v1-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /usr/local/Homebrew
            - /usr/local/Caskroom/xquartz
            - /usr/local/Cellar/wine
            - /usr/local/Cellar/node

  # build app dependancies
  build_app_dependencies:
    executor: mac-executor
    steps:
      # restore codebase
      - restore_cache:
          keys:
            - repo-v1-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - repo-v1-

      # restore brew cache
      - restore_cache:
          keys:
            - homebrew-v1-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - homebrew-v1-{{ .Branch }}-
            - homebrew-v1-
      # yarn install
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      # yarn cache
      - run:
          name: Yarn Install
          command: yarn install
      - save_cache:
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  # build application
  # TODO: breakout into w seperate work-flows
  build_application:
    executor: mac-executor
    steps:
      # restore codebase
      - restore_cache:
          keys:
            - repo-v1-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - repo-v1-

      # restore brew cache
      - restore_cache:
          keys:
            - homebrew-v1-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - homebrew-v1-{{ .Branch }}-
            - homebrew-v1-
      # yarn cache
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run: make clean all
      # cache built apps
      - save_cache:
          key: app-dist-v1-{{ .Branch }}-{{ checksum "dist/latest-mac.yml" }}
          paths:
            - ~/dist

  # run tests
  # TODO: breakout into w seperate work-flows
  run_application_tests:
    executor: mac-executor
    steps:
      # restore codebase
      - restore_cache:
          keys:
            - repo-v1-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - repo-v1-

      # restore brew cache
      - restore_cache:
          keys:
            - homebrew-v1-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - homebrew-v1-{{ .Branch }}-
            - homebrew-v1-
      # yarn cache
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      # app cache
      - restore_cache:
          keys:
            - app-dist-v1-{{ .Branch }}-{{ checksum "dist/latest-mac.yml" }}
            - app-dist-v1-
      # run tests
      - run: make test
      # TODO: cache results

  # upload artifacts to circle * if not master
  upload_application_artifacts:
    executor: mac-executor
    steps:
      # restore codebase
      - restore_cache:
          keys:
            - repo-v1-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - repo-v1-

      # restore brew cache
      - restore_cache:
          keys:
            - homebrew-v1-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - homebrew-v1-{{ .Branch }}-
            - homebrew-v1-
      # yarn cache
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      # app cache
      - restore_cache:
          keys:
            - app-dist-v1-{{ .Branch }}-{{ checksum "dist/latest-mac.yml" }}
            - app-dist-v1-
      - run:
          name: tar/zip up artifacts and make hashes
          command: ./.circleci/generate_artifacts.sh $ARTIFACTS
      - store_artifacts:
          path: /artifacts

  # build release - * if master branch
  upload_application_release:
    executor: mac-executor
    steps:
      # restore codebase
      - restore_cache:
          keys:
            - repo-v1-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - repo-v1-

      # restore brew cache
      - restore_cache:
          keys:
            - homebrew-v1-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - homebrew-v1-{{ .Branch }}-
            - homebrew-v1-
      # yarn cache
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      # app cache
      - restore_cache:
          keys:
            - app-dist-v1-{{ .Branch }}-{{ checksum "dist/latest-mac.yml" }}
            - app-dist-v1-
      - run:
          name: upload release
          command: yarn run release

  # TODO: nightly_build

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - build_env_dependencies:
          requires:
            - checkout_code
      - build_app_dependencies:
          requires:
            - build_env_dependencies
      - build_application:
          requires:
            - build_app_dependencies
      - run_application_tests:
          requires:
            - build_app_dependencies
      - upload_application_artifacts:
          requires:
            - build_app_dependencies
      - upload_application_release:
          requires:
            - build_app_dependencies
