defaults: &defaults
  macos:
    xcode: "10.0.0"
  environment:
    ARTIFACTS: /artifacts
  working_directory: ~/ddev-ui

aliases:
  # Source: restore
  - &restore_source
    restore_cache:
      keys:
        - v2-source-{{ .Branch }}-{{ .Revision }}
        - v2-source-{{ .Branch }}-
  # Source: cache
  - &cache_source
    save_cache:
      key: v2-source-{{ .Branch }}-{{ .Revision }}
      paths:
        - ".git"
        - ~/ddev-ui

  # Brew: restore
  - &restore_brew
    restore_cache:
      keys:
        - v2-homebrew-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
        - v2-homebrew-{{ .Branch }}-
  # Brew: cache
  - &cache_brew
    save_cache:
      key: v2-homebrew-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      paths:
        - /usr/local/Cellar/rpm

  # Yarn: restore
  - &restore_yarn
    restore_cache:
      keys:
        - v2-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - v2-yarn-packages-{{ .Branch }}-
  # Yarn: cache
  - &cache_yarn
    save_cache:
      key: v2-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
      paths:
        - ~/ddev-ui/node_modules

  # Display installed tools
  - &log_tools
    run:
      name: Installed tool versions
      command: >-
        echo "git commit=$(make version) node version=$(node --version) npm
        version=$(npm --version) wine version=$(wine --version) HOME=$HOME
        USER=$(whoami) PWD=$PWD"

version: 2.0
jobs:
  build:
    <<: *defaults
    steps:
      # Checkout the codebase
      - *restore_source
      - checkout
      - *cache_source

      # Homebrew Setup
      - *restore_brew
      - run: brew doctor
      - run: brew install rpm
      - *cache_brew

      # build app dependancies
      - *restore_yarn
      - run:
          name: Yarn Install
          command: yarn install
      - *cache_yarn

      ## echo installed tools
      - *log_tools

      # build apps
      - run: make
      # - run: make all

  test:
    <<: *defaults
    steps:
      - *restore_source
      - checkout
      - *restore_brew
      - run: brew update
      - *restore_yarn
      - run: yarn install
      - *log_tools

      # run tests
      - run: make test

  artifacts:
    <<: *defaults
    steps:
      - *restore_source
      - checkout
      - *restore_brew
      - run: brew update
      - *restore_yarn
      - run: yarn install
      - *log_tools

      # upload artifacts to circleci
      - run:
          command: ./.circleci/generate_artifacts.sh $ARTIFACTS
          name: tar/zip up artifacts and make hashes
      - store_artifacts:
          path: /artifacts

  release:
    <<: *defaults
    steps:
      - *restore_source
      - checkout
      - *restore_brew
      - run: brew update
      - *restore_yarn
      - run: yarn install
      - *log_tools

      # make release
      - run: make release-darwin

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - artifacts:
          requires:
            - build
            - test
          filters:
            branches:
              ignore:
                - master
      - release:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - master
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
